### PR TITLE
[#60] test report encoding from config

### PR DESCRIPTION
**Pull request by kreuzberger**
Add configuration value for encoding of reading files

### CODE REVIEW

**Comment by kreuzberger** [comment]
Der Linter schlägt fehl wegen einer pip abhängigkeit, nicht wegen dem linten.

Wenn ich flake und isort auf dem repo mache (make format) dann ändert sich sehr viel.

**Comment by danwos** [comment]
Thanks for the quick PR. It really looks good and it will get merged.

The only thing, which  is missing, is an entry in the changelog :)

Thanks for your support here.
I really appreciate the way you also add great test cases to your changes :+1:

**Comment by danwos** [comment]
> Der Linter schlägt fehl wegen einer pip abhängigkeit, nicht wegen dem linten.
> 
> Wenn ich flake und isort auf dem repo mache (make format) dann ändert sich sehr viel.

Argh, I know this bug. Some dependency versions are not compatible with the newer poetry version, whicjh is now more strict for some version-strings. I'm on it....

**Comment by kreuzberger** [comment]
Thanks for the compliment. Updated changelog as requested. Could you full format the code so that only things changed by the future PR's are changed by format? Or do you have different setting (i just call `make format`)

**Comment by danwos** [comment]
Created a new PR #62, which contains all your changes and also the updated rules and versions for linting.
(maybe not my smartest decision to do it that way).

So I think we can close this PR and work on #62

**Pull request closed without merging**
